[build]    
  publish   = "."            # everything under demo/ is your site    
  functions = "functions"    # point Netlify at demo/functions/    
    
[dev]    
  port = 8888                # (optional)    