[build]    
  publish   = "."           # everything under demo2/ is your site    
  functions = "functions"   # where fetch-pdf.js lives    
  command = "echo 'Static site ready'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404